{
  imports = [
    ./boot.nix
    ./desktop.nix
    ./docker.nix
    ./fonts.nix
    ./locale.nix
    ./networking.nix
    ./nvidia.nix
    ./packages.nix
    ./power.nix
    ./sound.nix
    ./users.nix
    ./input.nix
    ./game.nix
    ./i3/i3.nix
    ./openbox/openbox.nix
  ];
}
