#!/usr/bin/env sh

xset r rate 200 35
xrandr --output eDP --mode 1920x1080 --rate 60
# Kill old processes
pkill -x sxhkd
pkill -x picom

# Start daemons
sxhkd &
~/.config/polybar/launch.sh &
picom &

# Wallpaper
feh --bg-fill ~/personal/wallpapers/ggs.png &

# Desktops
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Appearance
bspc config border_width         2
bspc config window_gap           10
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Focus
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false

# Window behavior
bspc config click_to_focus button1
bspc config swallow_first_click false

# New windows
bspc config automatic_scheme longest_side
bspc config initial_polarity second_child

# Floating dialogs
bspc rule -a "*" state=tilting center=on
bspc rule -a Gimp state=floating
bspc rule -a librewolf state=floating
bspc rule -a feh state=floating
bspc rule -a pavucontrol state=floating
bspc rule -a blueman-manager state=floating
bspc rule -a snapshot state=floating
