 monitor = eDP-1,1920x1080@60,0x0,1.0

$mainMod = SUPER
$terminal = foot
$menu = rofi -show drun

exec-once = swayidle -w \
    timeout 400 "hyprctl dispatch dpms off" \
    resume "hyprctl dispatch dpms on" \
    before-sleep "loginctl lock-session"

exec-once = waybar
exec-once = swaync
exec-once = awww-daemon & sleep 0.1 & awww ~/personal/wallpapers/ggs.jpg

env = LIBVA_DRIVER_NAME,radeonsi
env = VDPAU_DRIVER,radeonsi
env = GTK_ICON_THEME,Adwaita
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland

general {
    gaps_in = 2
    gaps_out = 5
    border_size = 1
    resize_on_border = true
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 0
    rounding_power = 0
    active_opacity = 1.0
    inactive_opacity = 1.0
    dim_inactive = false

    blur {
        enabled = false
    }
}

animations {
    enabled = false
}

misc {
    force_default_wallpaper = -1
    disable_hyprland_logo = true
}

input {
    kb_layout = us
    follow_mouse = 1
    sensitivity = 0.4
    repeat_rate = 50
    repeat_delay = 200

    touchpad {
        natural_scroll = false
    }
}

cursor {
    inactive_timeout = 30
    no_hardware_cursors = false
}


bind = $mainMod, Return, exec, $terminal
bind = $mainMod, E, exec, pgrep waybar >/dev/null && pkill waybar || waybar
bind = $mainMod, D, exec, $menu
bind = $mainMod, F, fullscreen, 1
bind = $mainMod, V, togglefloating
bind = $mainMod SHIFT, Q, killactive
bind = $mainMod, M, exit
bind = $mainMod SHIFT, R, exec, hyprctl reload

bind = $mainMod, H, movefocus, l
bind = $mainMod, J, movefocus, d
bind = $mainMod, K, movefocus, u
bind = $mainMod, L, movefocus, r

bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, J, movewindow, d
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, L, movewindow, r

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic

bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+ && notify-send -h string:x-canonical-private-synchronous:brightness "☀ Brightness" "$(brightnessctl -m | awk -F, '{print $4}')"
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%- && notify-send -h string:x-canonical-private-synchronous:brightness "☀ Brightness" "$(brightnessctl -m | awk -F, '{print $4}')"

bind = ,XF86AudioRaiseVolume, exec, pamixer -i 5 && notify-send -h string:x-canonical-private-synchronous:volume "󰕾 Volume" "$(pamixer --get-volume)%"
bind = ,XF86AudioLowerVolume, exec, pamixer -d 5 && notify-send -h string:x-canonical-private-synchronous:volume "󰕾 Volume" "$(pamixer --get-volume)%"
bind = ,XF86AudioMute, exec, pamixer -t && notify-send -h string:x-canonical-private-synchronous:volume "󰖁 Volume" "$(pamixer --get-mute && echo Muted || pamixer --get-volume)%"

bind = $mainMod, N, exec, swaync-client -t
bind = $mainMod SHIFT, N, exec, swaync-client -d
bind = $mainMod CTRL, N, exec, swaync-client -C
